### ISSUE TITLE
IIS servers shows up as down instead of up

### ISSUE THREAD

**Issue by Larsje3112** [mojeda/ServerStatus#15]
![schermafbeelding 2015-02-02 om 21 12 07](https://cloud.githubusercontent.com/assets/6806973/6008229/3735b856-ab20-11e4-91b4-73d5e6c0999e.png)

The IIS server shows up as down instead of up while PHP exec works and the script also works on my Apache Server.

Best Regards,
Lars

**Comment by mojeda** [comment]
ServerStatus does not currently support windows servers. It's unlikely that I will add support for it in Server Status 2.0, however it's one of the things I'm working on in SS 3.0.

Uptime.php by default utilizes linux files to gather data and unfortunately I do not think windows offers this same flexibility while just using uptime.php.
