### ISSUE TITLE
Host is missing from README.md

### ISSUE THREAD

**Issue by purecanuck** [mojeda/ServerStatus#16]
Section 5 of Installation is missing host: 
5. Insert an entry into the database.
  * name - The name of your server.
  * url - The URL path to the uptime.php file (minus uptime.php and http://) e.g. dns.domain.tld/path/
  * location - Where is your server physically located?
  * type - What type of server is this? DNS, SQL, Apache/nginx, etc.

**Comment by mojeda** [comment]
added

**Comment by purecanuck** [comment]
It is still not obvious if host means ISP, hostname (FQDN) , or software your host is using?
