### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by KevinXuzio** [mojeda/ServerStatus#19]
Warning: fopen(/proc/uptime): failed to open stream: No such file or directory in C:\Users\root\Desktop\www\status\uptime.php on line 11

Warning: fgets() expects parameter 1 to be resource, boolean given in C:\Users\root\Desktop\www\status\uptime.php on line 12

Warning: fclose() expects parameter 1 to be resource, boolean given in C:\Users\root\Desktop\www\status\uptime.php on line 13

Warning: fopen(/proc/meminfo): failed to open stream: No such file or directory in C:\Users\root\Desktop\www\status\uptime.php on line 18

Warning: fgets() expects parameter 1 to be resource, boolean given in C:\Users\root\Desktop\www\status\uptime.php on line 20

Warning: fclose() expects parameter 1 to be resource, boolean given in C:\Users\root\Desktop\www\status\uptime.php on line 33

Notice: Undefined variable: memfree in C:\Users\root\Desktop\www\status\uptime.php on line 35

Notice: Undefined variable: memcache in C:\Users\root\Desktop\www\status\uptime.php on line 35

Notice: Undefined variable: memtotal in C:\Users\root\Desktop\www\status\uptime.php on line 36

Warning: Division by zero in C:\Users\root\Desktop\www\status\uptime.php on line 36

Fatal error: Call to undefined function sys_getloadavg() in C:\Users\root\Desktop\www\status\uptime.php on line 61

**Comment by mojeda** [comment]
ServerStatus does not support Windows servers at this time.
